kind: "Template"
apiVersion: "v1"
metadata: 
  name: "nginx"
  creationTimestamp: null
  annotations: 
    name: "Nginx server"
    description: "Nginx server template with php-fpm"
    iconClass: "icon-php"
    tags: "webserver,nginx,php"
objects: 
  - 
    kind: "Service"
    apiVersion: "v1"
    metadata:
      name: "${SERVICE_NAME}"
    spec:
      ports:
        - name: "nginx-server"
          protocol: "TCP"
          port: 80
          targetPort: 8080
      selector:
        name: "${SERVICE_NAME}"
      type: "ClusterIP"
    status: 
      loadBalancer: {}
  - 
    kind: "DeploymentConfig"
    apiVersion: "v1"
    metadata: 
      name: "${SERVICE_NAME}"
      creationTimestamp: null
    spec: 
      strategy:
        type: "Recreate"
      triggers: 
        - 
          type: "ImageChange"
          imageChangeParams: 
            automatic: true
            containerNames: 
              - nginx
            from:
              kind: "ImageStreamTag"
              name: "prod-${IMAGE_NAME}-nginx:${IMAGE_VERSION}"
              namespace: "${NAMESPACE}"
            lastTriggeredImage: ""
        - 
          type: "ImageChange"
          imageChangeParams: 
            automatic: true
            containerNames: 
              - php
            from:
              kind: "ImageStreamTag"
              name: "prod-${IMAGE_NAME}-phpfpm:${IMAGE_VERSION}"
              namespace: "${NAMESPACE}"
            lastTriggeredImage: ""
        - 
          type: "ConfigChange"
      replicas: 1
      selector: 
        name: "${SERVICE_NAME}"
      template: 
        metadata: 
          creationTimestamp: null
          labels: 
            name: "${SERVICE_NAME}"
        spec: 
          containers: 
            - name: nginx
              image: "oshanrube/prod-${IMAGE_NAME}-nginx:${IMAGE_VERSION}"
              ports:
                - name: "nginx-server"
                  containerPort: 8080
                  protocol: "TCP"
              resources: 
                requests:
                  memory: "64Mi"
                limits: 
                  memory: "${MEMORY_LIMIT}"
              terminationMessagePath: "/dev/termination-log"
              imagePullPolicy: "IfNotPresent"
              capabilities: {}
              securityContext: 
                capabilities: {}
                privileged: false
            - name: php
              image: "oshanrube/prod-${IMAGE_NAME}-phpfpm:${IMAGE_VERSION}"
              ports:
                - containerPort: 9000
                  protocol: "TCP"
              resources: 
                requests:
                  memory: "64Mi"
                limits: 
                  memory: "${MEMORY_LIMIT}"
              terminationMessagePath: "/dev/termination-log"
              imagePullPolicy: "IfNotPresent"
              capabilities: {}
              securityContext: 
                capabilities: {}
                privileged: false
          restartPolicy: "Always"
          dnsPolicy: "ClusterFirst"
    status: {}
parameters: 
  - 
    name: "NAMESPACE"
    displayName: "Namespace"
    description: "The OpenShift Namespace where the ImageStream resides."
    value: "oshanrube"
  - 
    name: "SERVICE_NAME"
    displayName: "Service Name"
    description: "The name of the Service exposed for the nginx."
    value: "nginx"
    required: true
  - 
    name: "IMAGE_NAME"
    displayName: "Image Name"
    description: "The name of the published image for the server."
    value: "nginx"
    required: true
  - 
    name: "IMAGE_VERSION"
    displayName: "Image version"
    description: "The version of the published image for the server."
    value: "1"
    required: true
  - 
    name: "MEMORY_LIMIT"
    displayName: "Memory Limit"
    description: "Maximum amount of memory the container can use."
    value: "256Mi"
labels: 
  template: "nginx-template"
